Do not use h3 tag for PostUser name
FriendsOfFlarum/gamification pull request #104
Opened 2023-03-12 13:19 UTC by rob006

Adjustments for https://github.com/flarum/framework/pull/3732

1. It uses class name instead of targeting h3 tag in `find()` call, so code should work after planned changes in Flarum 2.0.
2. I switched used tag from h3 to div - this was originally planed in core, but was postponed to 2.0 because of BC break. In case of this extension BC break should have much less impact than in core, so it may be OK to switch early to markup planned for Flarum 2.0.

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

2024-10-05 17:47 UTC, DavideIadeluca commented on js/src/forum/components/RankingsPage.js
> +                          <div className="PostUser-name rankings-info">
```suggestion
                          <h3 className="PostUser-name rankings-info">
```

2024-10-05 17:47 UTC, DavideIadeluca commented on js/src/forum/components/RankingsPage.js
> +                          </div>
```suggestion
                          </h3>
```

2024-10-05 17:47 UTC, DavideIadeluca requested changes
Sorry @rob006 it's been a while..

I had some thoughts about this and generally I agree with what you've outlined here and in https://github.com/flarum/framework/pull/3732.

Even though the impact of this change would me much smaller than in core, I'm still not comfortable with making that change right now, as it will inevitably break existing UI styling.

Therefore I would aim that we change this to a `<div>` only when we refactor the Extension for Flarum `2.x` and keep it a `h3` until then (with the newly added class).

2024-10-06 17:00 UTC, rob006 commented
I reverted tag change.

2024-10-07 04:41 UTC, DavideIadeluca approved these changes

2024-10-07 04:43 UTC, merged

2024-10-07 04:43 UTC, DavideIadeluca commented
Follow up issue to use <div> is created: https://github.com/FriendsOfFlarum/gamification/issues/125