Add new option to hide voting when not allowed
FriendsOfFlarum/gamification pull request #113
Opened 2023-12-05 18:47 UTC by hackerESQ

**Fixes #32** 

**Changes proposed in this pull request:**
This adds a new option in extension settings that allows admins to hide voting options when the post/tag/user does not have permissions to vote.

**Reviewers should focus on:**
This only adds a new configuration option. But perhaps the logic to hide should be reviewed:

```js
if (setting('hideIfNoPermissions', true) && !post.canVote() && !post.canSeeVotes()) {
   return;
}
```

This same logic was added to the alternate layout as well.

**Screenshot**
<img width="687" alt="image" src="https://github.com/FriendsOfFlarum/gamification/assets/16628119/f81b2eee-f8ad-4043-8b39-dd0a36953678">

**Confirmed**

- [X] Frontend changes: tested on a local Flarum installation.
- [X] Backend changes: tests are green (run `composer test`).

**Required changes:**
N/A

2023-12-12 14:48 UTC, imorland requested changes
Hello and thank you for the PR!

Looks good to me, but can you please remove the dist files from this? In order to keep merging as straightforward as possible, the js will be automatically built once merged :)

2023-12-13 00:09 UTC, hackerESQ commented
Sounds good! Let me know if that works!

2024-02-29 18:40 UTC, DavideIadeluca commented
Hi @hackerESQ, similarly like in https://github.com/FriendsOfFlarum/gamification/pull/114 this PR has merge conflicts. Please reset the history to the first commit you made on this branch, amend it and force push without the dist files being changed. Thanks!

2024-10-05 17:30 UTC, DavideIadeluca commented
It's been a while.. I had some thoughts about this, and I feel like adding another setting would make the already opaque permission/settings handling even worse.

I think for the next major release of this extension we should make the extension more opinionated by default but improve the extensibility of it.

Therefore, I'm actually inclined to close this PR because I'm not willing to maintain this. Thoughts @imorland?

2025-03-04 18:35 UTC, closed without merging