Fix json encode null
FriendsOfFlarum/gamification pull request #120
Opened 2024-07-06 04:37 UTC by datlechin

Fix json encode null

**Fixes #0000**

**Changes proposed in this pull request:**

**Reviewers should focus on:**

**Screenshot**

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related [Flarum core extension PR's](https://github.com/flarum/core/pulls): (Omit this section if irrelevant)

2024-07-23 16:55 UTC, DavideIadeluca requested changes
I'm fine with this, but I think it would make sense to simplify the surrounding logic a little:

```
public function handle(SettingsRepositoryInterface $settings, Dispatcher $dispatcher)
{
    $autoAssignGroups = $settings->get('fof-gamification.autoAssignedGroups');
    
    // If the setting is missing or empty, or if the subject user is an admin, we can skip this job
    if (empty($autoAssignGroups) || $this->user->isAdmin()) {
        return;
    }

    $entries = json_decode($autoAssignGroups, true);
..
}
```

2024-07-23 19:00 UTC, DavideIadeluca approved these changes
Thanks @datlechin!

2024-07-24 08:10 UTC, luceos commented
@DavideIadeluca if you want to do an optimization, although just a slight one, stop early instead of accessing the settings repository first (which you then don't need for an admin):

```php
        if ($this->user->isAdmin()) return;

        return json_decode(
                $settings->get('fof-gamification.autoAssignGroups', ''),
                true
        );
```

2024-10-05 16:57 UTC, DavideIadeluca approved these changes

2024-10-05 16:59 UTC, merged